set_property PACKAGE_PIN T22 [get_ports {output_vector[0]}]
set_property PACKAGE_PIN T21 [get_ports {output_vector[1]}]
set_property PACKAGE_PIN U22 [get_ports {output_vector[2]}]
set_property PACKAGE_PIN U21 [get_ports {output_vector[3]}]
set_property PACKAGE_PIN V22 [get_ports {output_vector[4]}]
set_property PACKAGE_PIN W22 [get_ports {output_vector[5]}]
set_property PACKAGE_PIN U19 [get_ports {output_vector[6]}]
set_property PACKAGE_PIN U14 [get_ports {output_vector[7]}]
set_property PACKAGE_PIN N15 [get_ports decrease]
set_property PACKAGE_PIN R18 [get_ports increase]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_vector[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports decrease]
set_property IOSTANDARD LVCMOS18 [get_ports increase]





set_property PACKAGE_PIN T18 [get_ports {speed_control_in[0]}]
set_property PACKAGE_PIN P16 [get_ports {speed_control_in[1]}]
set_property PACKAGE_PIN R16 [get_ports {speed_control_in[2]}]
set_property PACKAGE_PIN R18 [get_ports {tail_size[0]}]
set_property PACKAGE_PIN N15 [get_ports {tail_size[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tail_size[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {tail_size[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_output[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_control_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_control_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {speed_control_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports clockwise]
set_property PACKAGE_PIN F22 [get_ports clockwise]
set_property PACKAGE_PIN T22 [get_ports {leds_output[0]}]
set_property PACKAGE_PIN T21 [get_ports {leds_output[1]}]
set_property PACKAGE_PIN U22 [get_ports {leds_output[2]}]
set_property PACKAGE_PIN U21 [get_ports {leds_output[3]}]
set_property PACKAGE_PIN V22 [get_ports {leds_output[4]}]
set_property PACKAGE_PIN W22 [get_ports {leds_output[5]}]
set_property PACKAGE_PIN U19 [get_ports {leds_output[6]}]
set_property PACKAGE_PIN U14 [get_ports {leds_output[7]}]
